version: "3"
services:
  react-app:
    build: ./react-app
    container_name: sirh-front
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - sirh-app
    depends_on:
      - api-server
  api-server:
    build: ./api-server
    container_name: back-sirh
    ports:
      - "5000:5000"
    networks:
      - sirh-app
    depends_on:
      - mysql
  mysql:
    platform: linux/amd64
    image: mysql:latest
    container_name: mysql-sirh
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sirh-db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - sirh_data:/var/lib/mysql
    networks:
      - sirh-app
  phpmyadmin:
    platform: linux/amd64
    image: beeyev/phpmyadmin-lightweight:latest
    container_name: phpmyadmin-sirh
    restart: unless-stopped
    tty: true
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PASSWORD: root
    ports:
      - '8080:80'
    depends_on:
      - mysql
    networks:
      - sirh-app
  minio:
    platform: linux/amd64
    image: 'minio/minio:latest'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "8900:8900"
    container_name: minio-sirh
    volumes:
      - "sirh_data:/data/minio"
    networks:
      - sirh-app
    command: "minio server /data/minio --console-address ':8900'"
networks:
  sirh-app:
    driver: bridge
volumes:
  sirh_data:
    driver: local